version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
      labels:
        com.docker.buildkit.version: "1"
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=/api
    depends_on:
      - backend
    networks:
      - motorcycle-network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
      labels:
        com.docker.buildkit.version: "1"
    working_dir: /app
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DATABASE_URL=database/database.db
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CORS_ORIGIN=http://localhost:3000
    volumes:
      - ./backend/database:/app/database
      - ./backend/uploads:/app/uploads
      - ./backend/src:/app/src
      - ./backend/.env:/app/.env
    depends_on:
      - redis
    networks:
      - motorcycle-network
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - motorcycle-network
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  redis-data:

networks:
  motorcycle-network:
    driver: bridge
