version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
      labels:
        com.docker.buildkit.version: "1"
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=/api
      - VITE_GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY:-default_key}
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend
    networks:
      - motorcycle-network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
      labels:
        com.docker.buildkit.version: "1"
    working_dir: /app
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DATABASE_URL=database/database.db
      - JWT_SECRET=${JWT_SECRET:-development_secret_key}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CORS_ORIGIN=http://localhost:3000
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-default_key}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-default_secret}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME:-default-bucket}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY:-default_key}
      - MAX_FILE_SIZE=5242880
      - CACHE_TTL=3600
    volumes:
      - ./backend/database:/app/database
      - ./backend/uploads:/app/uploads
      - ./backend/src:/app/src
      - ./backend/.env:/app/.env
      - ./backend/cache:/app/cache
      - ./gallery:/app/uploads/gallery
    depends_on:
      - redis
    networks:
      - motorcycle-network
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - motorcycle-network
    restart: unless-stopped

volumes:
  redis-data:

networks:
  motorcycle-network:
    driver: bridge
